[package]
name = "tokenise-cap-table"
version = "0.0.0"
edition = "2021"
publish = false


[dependencies]
soroban-sdk = "22.0.0"
soroban-token-sdk = "22.0.0"


[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
